# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 760)
        MainWindow.setMinimumSize(QtCore.QSize(500, 650))
        MainWindow.setMaximumSize(QtCore.QSize(600, 100000))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle("K1921VKx Flasher")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/flasher.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.vbox_options = QtWidgets.QVBoxLayout()
        self.vbox_options.setObjectName("vbox_options")
        self.gbox_connect = QtWidgets.QGroupBox(self.centralwidget)
        self.gbox_connect.setObjectName("gbox_connect")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gbox_connect)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.hbox_port = QtWidgets.QHBoxLayout()
        self.hbox_port.setObjectName("hbox_port")
        self.btn_updport = QtWidgets.QPushButton(self.gbox_connect)
        self.btn_updport.setMinimumSize(QtCore.QSize(21, 0))
        self.btn_updport.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_updport.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_updport.setIcon(icon1)
        self.btn_updport.setObjectName("btn_updport")
        self.hbox_port.addWidget(self.btn_updport)
        self.combo_port = QtWidgets.QComboBox(self.gbox_connect)
        self.combo_port.setMaximumSize(QtCore.QSize(16777215, 23))
        self.combo_port.setObjectName("combo_port")
        self.hbox_port.addWidget(self.combo_port)
        self.combo_baud = QtWidgets.QComboBox(self.gbox_connect)
        self.combo_baud.setMaximumSize(QtCore.QSize(80, 23))
        self.combo_baud.setObjectName("combo_baud")
        self.combo_baud.addItem("")
        self.combo_baud.setItemText(0, "9600")
        self.combo_baud.addItem("")
        self.combo_baud.setItemText(1, "19200")
        self.combo_baud.addItem("")
        self.combo_baud.setItemText(2, "38400")
        self.combo_baud.addItem("")
        self.combo_baud.setItemText(3, "57600")
        self.combo_baud.addItem("")
        self.combo_baud.setItemText(4, "115200")
        self.combo_baud.addItem("")
        self.combo_baud.setItemText(5, "230400")
        self.combo_baud.addItem("")
        self.combo_baud.setItemText(6, "460800")
        self.combo_baud.addItem("")
        self.combo_baud.setItemText(7, "921600")
        self.hbox_port.addWidget(self.combo_baud)
        self.horizontalLayout_3.addLayout(self.hbox_port)
        self.btn_connect = QtWidgets.QPushButton(self.gbox_connect)
        self.btn_connect.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_connect.setMaximumSize(QtCore.QSize(150, 23))
        self.btn_connect.setText("Подключиться")
        self.btn_connect.setObjectName("btn_connect")
        self.horizontalLayout_3.addWidget(self.btn_connect)
        self.vbox_options.addWidget(self.gbox_connect)
        self.hbox_selection = QtWidgets.QHBoxLayout()
        self.hbox_selection.setObjectName("hbox_selection")
        self.gbox_flash = QtWidgets.QGroupBox(self.centralwidget)
        self.gbox_flash.setEnabled(False)
        self.gbox_flash.setObjectName("gbox_flash")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbox_flash)
        self.verticalLayout.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hbox_flash_select = QtWidgets.QHBoxLayout()
        self.hbox_flash_select.setObjectName("hbox_flash_select")
        self.rbtn_flash0 = QtWidgets.QRadioButton(self.gbox_flash)
        self.rbtn_flash0.setMaximumSize(QtCore.QSize(16777215, 21))
        self.rbtn_flash0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rbtn_flash0.setAutoFillBackground(False)
        self.rbtn_flash0.setText("FLASH0")
        self.rbtn_flash0.setChecked(True)
        self.rbtn_flash0.setObjectName("rbtn_flash0")
        self.hbox_flash_select.addWidget(self.rbtn_flash0)
        self.rbtn_flash1 = QtWidgets.QRadioButton(self.gbox_flash)
        self.rbtn_flash1.setMaximumSize(QtCore.QSize(16777215, 21))
        self.rbtn_flash1.setText("FLASH1")
        self.rbtn_flash1.setObjectName("rbtn_flash1")
        self.hbox_flash_select.addWidget(self.rbtn_flash1)
        self.verticalLayout.addLayout(self.hbox_flash_select)
        self.hbox_selection.addWidget(self.gbox_flash)
        self.gbox_region = QtWidgets.QGroupBox(self.centralwidget)
        self.gbox_region.setEnabled(False)
        self.gbox_region.setObjectName("gbox_region")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.gbox_region)
        self.verticalLayout_10.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.hbox_region = QtWidgets.QHBoxLayout()
        self.hbox_region.setObjectName("hbox_region")
        self.rbtn_regionmain = QtWidgets.QRadioButton(self.gbox_region)
        self.rbtn_regionmain.setMaximumSize(QtCore.QSize(16777215, 21))
        self.rbtn_regionmain.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rbtn_regionmain.setAutoFillBackground(False)
        self.rbtn_regionmain.setText("Основная")
        self.rbtn_regionmain.setChecked(True)
        self.rbtn_regionmain.setObjectName("rbtn_regionmain")
        self.hbox_region.addWidget(self.rbtn_regionmain)
        self.rbtn_regionnvr = QtWidgets.QRadioButton(self.gbox_region)
        self.rbtn_regionnvr.setMaximumSize(QtCore.QSize(16777215, 21))
        self.rbtn_regionnvr.setText("NVR / Info")
        self.rbtn_regionnvr.setObjectName("rbtn_regionnvr")
        self.hbox_region.addWidget(self.rbtn_regionnvr)
        self.verticalLayout_10.addLayout(self.hbox_region)
        self.hbox_selection.addWidget(self.gbox_region)
        self.vbox_options.addLayout(self.hbox_selection)
        self.verticalLayout_12.addLayout(self.vbox_options)
        self.tabs_cmd = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs_cmd.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs_cmd.sizePolicy().hasHeightForWidth())
        self.tabs_cmd.setSizePolicy(sizePolicy)
        self.tabs_cmd.setMinimumSize(QtCore.QSize(488, 320))
        self.tabs_cmd.setMaximumSize(QtCore.QSize(16777215, 320))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabs_cmd.setFont(font)
        self.tabs_cmd.setObjectName("tabs_cmd")
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_info.sizePolicy().hasHeightForWidth())
        self.tab_info.setSizePolicy(sizePolicy)
        self.tab_info.setMaximumSize(QtCore.QSize(16777215, 480))
        self.tab_info.setObjectName("tab_info")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_info)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tinfo_hbox_info = QtWidgets.QHBoxLayout()
        self.tinfo_hbox_info.setObjectName("tinfo_hbox_info")
        self.tinfo_hbox_info_values = QtWidgets.QFormLayout()
        self.tinfo_hbox_info_values.setObjectName("tinfo_hbox_info_values")
        self.tinfo_lab_chipid = QtWidgets.QLabel(self.tab_info)
        self.tinfo_lab_chipid.setMaximumSize(QtCore.QSize(16777215, 23))
        self.tinfo_lab_chipid.setText("CHIPID")
        self.tinfo_lab_chipid.setObjectName("tinfo_lab_chipid")
        self.tinfo_hbox_info_values.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tinfo_lab_chipid)
        self.tinfo_ledit_chipid = QtWidgets.QLineEdit(self.tab_info)
        self.tinfo_ledit_chipid.setMinimumSize(QtCore.QSize(90, 0))
        self.tinfo_ledit_chipid.setMaximumSize(QtCore.QSize(90, 23))
        self.tinfo_ledit_chipid.setText("0xFFFFFFFF")
        self.tinfo_ledit_chipid.setReadOnly(True)
        self.tinfo_ledit_chipid.setObjectName("tinfo_ledit_chipid")
        self.tinfo_hbox_info_values.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tinfo_ledit_chipid)
        self.tinfo_lab_cpuid = QtWidgets.QLabel(self.tab_info)
        self.tinfo_lab_cpuid.setMaximumSize(QtCore.QSize(16777215, 23))
        self.tinfo_lab_cpuid.setText("CPUID")
        self.tinfo_lab_cpuid.setObjectName("tinfo_lab_cpuid")
        self.tinfo_hbox_info_values.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tinfo_lab_cpuid)
        self.tinfo_ledit_cpuid = QtWidgets.QLineEdit(self.tab_info)
        self.tinfo_ledit_cpuid.setMinimumSize(QtCore.QSize(90, 0))
        self.tinfo_ledit_cpuid.setMaximumSize(QtCore.QSize(90, 23))
        self.tinfo_ledit_cpuid.setText("0xFFFFFFFF")
        self.tinfo_ledit_cpuid.setReadOnly(True)
        self.tinfo_ledit_cpuid.setObjectName("tinfo_ledit_cpuid")
        self.tinfo_hbox_info_values.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tinfo_ledit_cpuid)
        self.tinfo_lab_bootver = QtWidgets.QLabel(self.tab_info)
        self.tinfo_lab_bootver.setMaximumSize(QtCore.QSize(16777215, 23))
        self.tinfo_lab_bootver.setText("Версия загрузчика")
        self.tinfo_lab_bootver.setObjectName("tinfo_lab_bootver")
        self.tinfo_hbox_info_values.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tinfo_lab_bootver)
        self.tinfo_ledit_bootver = QtWidgets.QLineEdit(self.tab_info)
        self.tinfo_ledit_bootver.setMinimumSize(QtCore.QSize(90, 0))
        self.tinfo_ledit_bootver.setMaximumSize(QtCore.QSize(90, 23))
        self.tinfo_ledit_bootver.setText("0.0")
        self.tinfo_ledit_bootver.setReadOnly(True)
        self.tinfo_ledit_bootver.setObjectName("tinfo_ledit_bootver")
        self.tinfo_hbox_info_values.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tinfo_ledit_bootver)
        self.tinfo_hbox_info.addLayout(self.tinfo_hbox_info_values)
        self.tinfo_lab_mcu = QtWidgets.QLabel(self.tab_info)
        self.tinfo_lab_mcu.setMinimumSize(QtCore.QSize(150, 0))
        self.tinfo_lab_mcu.setMaximumSize(QtCore.QSize(16777215, 83))
        self.tinfo_lab_mcu.setText("К1921ВКххх")
        self.tinfo_lab_mcu.setObjectName("tinfo_lab_mcu")
        self.tinfo_hbox_info.addWidget(self.tinfo_lab_mcu)
        self.verticalLayout_5.addLayout(self.tinfo_hbox_info)
        self.tinfo_tbl_flash = QtWidgets.QTableWidget(self.tab_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tinfo_tbl_flash.sizePolicy().hasHeightForWidth())
        self.tinfo_tbl_flash.setSizePolicy(sizePolicy)
        self.tinfo_tbl_flash.setMaximumSize(QtCore.QSize(10000, 174))
        self.tinfo_tbl_flash.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tinfo_tbl_flash.setShowGrid(True)
        self.tinfo_tbl_flash.setCornerButtonEnabled(False)
        self.tinfo_tbl_flash.setObjectName("tinfo_tbl_flash")
        self.tinfo_tbl_flash.setColumnCount(5)
        self.tinfo_tbl_flash.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Номер")
        self.tinfo_tbl_flash.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Адрес")
        self.tinfo_tbl_flash.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Размер")
        self.tinfo_tbl_flash.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Ч")
        self.tinfo_tbl_flash.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("З")
        self.tinfo_tbl_flash.setHorizontalHeaderItem(4, item)
        self.tinfo_tbl_flash.horizontalHeader().setVisible(True)
        self.tinfo_tbl_flash.horizontalHeader().setCascadingSectionResizes(False)
        self.tinfo_tbl_flash.horizontalHeader().setDefaultSectionSize(84)
        self.tinfo_tbl_flash.horizontalHeader().setStretchLastSection(False)
        self.tinfo_tbl_flash.verticalHeader().setVisible(False)
        self.tinfo_tbl_flash.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_5.addWidget(self.tinfo_tbl_flash)
        self.tabs_cmd.addTab(self.tab_info, "Информация")
        self.tab_write = QtWidgets.QWidget()
        self.tab_write.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_write.sizePolicy().hasHeightForWidth())
        self.tab_write.setSizePolicy(sizePolicy)
        self.tab_write.setMaximumSize(QtCore.QSize(16777215, 480))
        self.tab_write.setObjectName("tab_write")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_write)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.twrite_frm_file = QtWidgets.QFrame(self.tab_write)
        self.twrite_frm_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.twrite_frm_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.twrite_frm_file.setObjectName("twrite_frm_file")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.twrite_frm_file)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.twrite_lab_fileopen = QtWidgets.QLabel(self.twrite_frm_file)
        self.twrite_lab_fileopen.setText("Выбор файла для постраничной записи (*.bin):")
        self.twrite_lab_fileopen.setObjectName("twrite_lab_fileopen")
        self.verticalLayout_3.addWidget(self.twrite_lab_fileopen)
        self.twrite_hbox_file = QtWidgets.QHBoxLayout()
        self.twrite_hbox_file.setObjectName("twrite_hbox_file")
        self.twrite_ledit_filepath = QtWidgets.QLineEdit(self.twrite_frm_file)
        self.twrite_ledit_filepath.setMaximumSize(QtCore.QSize(16777215, 23))
        self.twrite_ledit_filepath.setReadOnly(False)
        self.twrite_ledit_filepath.setObjectName("twrite_ledit_filepath")
        self.twrite_hbox_file.addWidget(self.twrite_ledit_filepath)
        self.twrite_btn_fileopen = QtWidgets.QPushButton(self.twrite_frm_file)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twrite_btn_fileopen.sizePolicy().hasHeightForWidth())
        self.twrite_btn_fileopen.setSizePolicy(sizePolicy)
        self.twrite_btn_fileopen.setMaximumSize(QtCore.QSize(20, 23))
        self.twrite_btn_fileopen.setText("...")
        self.twrite_btn_fileopen.setObjectName("twrite_btn_fileopen")
        self.twrite_hbox_file.addWidget(self.twrite_btn_fileopen)
        self.verticalLayout_3.addLayout(self.twrite_hbox_file)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.twrite_form_firstpage = QtWidgets.QFormLayout()
        self.twrite_form_firstpage.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.twrite_form_firstpage.setObjectName("twrite_form_firstpage")
        self.twrite_lab_addr = QtWidgets.QLabel(self.twrite_frm_file)
        self.twrite_lab_addr.setText("Адрес")
        self.twrite_lab_addr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.twrite_lab_addr.setObjectName("twrite_lab_addr")
        self.twrite_form_firstpage.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.twrite_lab_addr)
        self.twrite_ledit_addr = QtWidgets.QLineEdit(self.twrite_frm_file)
        self.twrite_ledit_addr.setMinimumSize(QtCore.QSize(90, 0))
        self.twrite_ledit_addr.setMaximumSize(QtCore.QSize(90, 23))
        self.twrite_ledit_addr.setText("0x00000000")
        self.twrite_ledit_addr.setReadOnly(False)
        self.twrite_ledit_addr.setObjectName("twrite_ledit_addr")
        self.twrite_form_firstpage.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.twrite_ledit_addr)
        self.twrite_lab_page = QtWidgets.QLabel(self.twrite_frm_file)
        self.twrite_lab_page.setText("Номер стр.:")
        self.twrite_lab_page.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.twrite_lab_page.setObjectName("twrite_lab_page")
        self.twrite_form_firstpage.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.twrite_lab_page)
        self.twrite_ledit_page = QtWidgets.QLineEdit(self.twrite_frm_file)
        self.twrite_ledit_page.setMinimumSize(QtCore.QSize(90, 0))
        self.twrite_ledit_page.setMaximumSize(QtCore.QSize(90, 23))
        self.twrite_ledit_page.setText("0")
        self.twrite_ledit_page.setReadOnly(False)
        self.twrite_ledit_page.setObjectName("twrite_ledit_page")
        self.twrite_form_firstpage.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.twrite_ledit_page)
        self.horizontalLayout_2.addLayout(self.twrite_form_firstpage)
        self.twrite_form_lastpage = QtWidgets.QFormLayout()
        self.twrite_form_lastpage.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.twrite_form_lastpage.setObjectName("twrite_form_lastpage")
        self.twrite_lab_size = QtWidgets.QLabel(self.twrite_frm_file)
        self.twrite_lab_size.setText("Размер (байт)")
        self.twrite_lab_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.twrite_lab_size.setObjectName("twrite_lab_size")
        self.twrite_form_lastpage.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.twrite_lab_size)
        self.twrite_ledit_size = QtWidgets.QLineEdit(self.twrite_frm_file)
        self.twrite_ledit_size.setMinimumSize(QtCore.QSize(90, 0))
        self.twrite_ledit_size.setMaximumSize(QtCore.QSize(90, 23))
        self.twrite_ledit_size.setText("0x00000000")
        self.twrite_ledit_size.setReadOnly(True)
        self.twrite_ledit_size.setObjectName("twrite_ledit_size")
        self.twrite_form_lastpage.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.twrite_ledit_size)
        self.twrite_lab_pages = QtWidgets.QLabel(self.twrite_frm_file)
        self.twrite_lab_pages.setText("Кол-во стр.:")
        self.twrite_lab_pages.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.twrite_lab_pages.setObjectName("twrite_lab_pages")
        self.twrite_form_lastpage.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.twrite_lab_pages)
        self.twrite_ledit_pages = QtWidgets.QLineEdit(self.twrite_frm_file)
        self.twrite_ledit_pages.setMinimumSize(QtCore.QSize(90, 0))
        self.twrite_ledit_pages.setMaximumSize(QtCore.QSize(90, 23))
        self.twrite_ledit_pages.setText("0")
        self.twrite_ledit_pages.setReadOnly(True)
        self.twrite_ledit_pages.setObjectName("twrite_ledit_pages")
        self.twrite_form_lastpage.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.twrite_ledit_pages)
        self.horizontalLayout_2.addLayout(self.twrite_form_lastpage)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addWidget(self.twrite_frm_file)
        self.twrite_frm_erase = QtWidgets.QFrame(self.tab_write)
        self.twrite_frm_erase.setMaximumSize(QtCore.QSize(16777215, 40))
        self.twrite_frm_erase.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.twrite_frm_erase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.twrite_frm_erase.setObjectName("twrite_frm_erase")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.twrite_frm_erase)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.twrite_rbtn_ernone = QtWidgets.QRadioButton(self.twrite_frm_erase)
        self.twrite_rbtn_ernone.setMaximumSize(QtCore.QSize(16777215, 23))
        self.twrite_rbtn_ernone.setText("Не стирать")
        self.twrite_rbtn_ernone.setObjectName("twrite_rbtn_ernone")
        self.horizontalLayout_6.addWidget(self.twrite_rbtn_ernone)
        self.twrite_rbtn_erall = QtWidgets.QRadioButton(self.twrite_frm_erase)
        self.twrite_rbtn_erall.setMaximumSize(QtCore.QSize(16777215, 23))
        self.twrite_rbtn_erall.setText("Стереть всё")
        self.twrite_rbtn_erall.setObjectName("twrite_rbtn_erall")
        self.horizontalLayout_6.addWidget(self.twrite_rbtn_erall)
        self.twrite_rbtn_erpages = QtWidgets.QRadioButton(self.twrite_frm_erase)
        self.twrite_rbtn_erpages.setMaximumSize(QtCore.QSize(16777215, 23))
        self.twrite_rbtn_erpages.setText("Стереть страницы")
        self.twrite_rbtn_erpages.setChecked(True)
        self.twrite_rbtn_erpages.setObjectName("twrite_rbtn_erpages")
        self.horizontalLayout_6.addWidget(self.twrite_rbtn_erpages)
        self.verticalLayout_7.addWidget(self.twrite_frm_erase)
        self.twrite_frm_opts = QtWidgets.QFrame(self.tab_write)
        self.twrite_frm_opts.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.twrite_frm_opts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.twrite_frm_opts.setObjectName("twrite_frm_opts")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.twrite_frm_opts)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.twrite_chbox_verif = QtWidgets.QCheckBox(self.twrite_frm_opts)
        self.twrite_chbox_verif.setMaximumSize(QtCore.QSize(16777215, 23))
        self.twrite_chbox_verif.setText("Верификация")
        self.twrite_chbox_verif.setChecked(True)
        self.twrite_chbox_verif.setObjectName("twrite_chbox_verif")
        self.verticalLayout_4.addWidget(self.twrite_chbox_verif)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.twrite_chbox_jump = QtWidgets.QCheckBox(self.twrite_frm_opts)
        self.twrite_chbox_jump.setEnabled(False)
        self.twrite_chbox_jump.setMaximumSize(QtCore.QSize(16777215, 23))
        self.twrite_chbox_jump.setText("Переход к исполнению по адресу")
        self.twrite_chbox_jump.setObjectName("twrite_chbox_jump")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.twrite_chbox_jump)
        self.twrite_ledit_jumpaddr = QtWidgets.QLineEdit(self.twrite_frm_opts)
        self.twrite_ledit_jumpaddr.setEnabled(False)
        self.twrite_ledit_jumpaddr.setMinimumSize(QtCore.QSize(90, 0))
        self.twrite_ledit_jumpaddr.setMaximumSize(QtCore.QSize(90, 23))
        self.twrite_ledit_jumpaddr.setText("0x00000000")
        self.twrite_ledit_jumpaddr.setReadOnly(False)
        self.twrite_ledit_jumpaddr.setObjectName("twrite_ledit_jumpaddr")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.twrite_ledit_jumpaddr)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.verticalLayout_7.addWidget(self.twrite_frm_opts)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.tabs_cmd.addTab(self.tab_write, "Запись")
        self.tab_erase = QtWidgets.QWidget()
        self.tab_erase.setEnabled(False)
        self.tab_erase.setMaximumSize(QtCore.QSize(16777215, 480))
        self.tab_erase.setObjectName("tab_erase")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_erase)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.terase_frm_erase = QtWidgets.QFrame(self.tab_erase)
        self.terase_frm_erase.setMaximumSize(QtCore.QSize(16777215, 40))
        self.terase_frm_erase.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.terase_frm_erase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.terase_frm_erase.setObjectName("terase_frm_erase")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.terase_frm_erase)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.terase_rbtn_erall = QtWidgets.QRadioButton(self.terase_frm_erase)
        self.terase_rbtn_erall.setMaximumSize(QtCore.QSize(16777215, 23))
        self.terase_rbtn_erall.setText("Стереть всё")
        self.terase_rbtn_erall.setChecked(True)
        self.terase_rbtn_erall.setObjectName("terase_rbtn_erall")
        self.horizontalLayout_7.addWidget(self.terase_rbtn_erall)
        self.terase_rbtn_erpages = QtWidgets.QRadioButton(self.terase_frm_erase)
        self.terase_rbtn_erpages.setMaximumSize(QtCore.QSize(16777215, 23))
        self.terase_rbtn_erpages.setText("Стереть страницы")
        self.terase_rbtn_erpages.setObjectName("terase_rbtn_erpages")
        self.horizontalLayout_7.addWidget(self.terase_rbtn_erpages)
        self.verticalLayout_6.addWidget(self.terase_frm_erase)
        self.terase_frm_addr = QtWidgets.QFrame(self.tab_erase)
        self.terase_frm_addr.setEnabled(False)
        self.terase_frm_addr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.terase_frm_addr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.terase_frm_addr.setObjectName("terase_frm_addr")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.terase_frm_addr)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.terase_form_firstpage = QtWidgets.QFormLayout()
        self.terase_form_firstpage.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.terase_form_firstpage.setObjectName("terase_form_firstpage")
        self.terase_lab_addr = QtWidgets.QLabel(self.terase_frm_addr)
        self.terase_lab_addr.setText("Адрес")
        self.terase_lab_addr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.terase_lab_addr.setObjectName("terase_lab_addr")
        self.terase_form_firstpage.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.terase_lab_addr)
        self.terase_ledit_addr = QtWidgets.QLineEdit(self.terase_frm_addr)
        self.terase_ledit_addr.setMinimumSize(QtCore.QSize(90, 0))
        self.terase_ledit_addr.setMaximumSize(QtCore.QSize(90, 23))
        self.terase_ledit_addr.setText("0x00000000")
        self.terase_ledit_addr.setReadOnly(False)
        self.terase_ledit_addr.setObjectName("terase_ledit_addr")
        self.terase_form_firstpage.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.terase_ledit_addr)
        self.terase_lab_page = QtWidgets.QLabel(self.terase_frm_addr)
        self.terase_lab_page.setText("Номер стр.:")
        self.terase_lab_page.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.terase_lab_page.setObjectName("terase_lab_page")
        self.terase_form_firstpage.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.terase_lab_page)
        self.terase_ledit_page = QtWidgets.QLineEdit(self.terase_frm_addr)
        self.terase_ledit_page.setMinimumSize(QtCore.QSize(90, 0))
        self.terase_ledit_page.setMaximumSize(QtCore.QSize(90, 23))
        self.terase_ledit_page.setText("0")
        self.terase_ledit_page.setReadOnly(False)
        self.terase_ledit_page.setObjectName("terase_ledit_page")
        self.terase_form_firstpage.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.terase_ledit_page)
        self.horizontalLayout.addLayout(self.terase_form_firstpage)
        self.terase_form_lastpage = QtWidgets.QFormLayout()
        self.terase_form_lastpage.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.terase_form_lastpage.setObjectName("terase_form_lastpage")
        self.terase_lab_size = QtWidgets.QLabel(self.terase_frm_addr)
        self.terase_lab_size.setText("Размер (байт)")
        self.terase_lab_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.terase_lab_size.setObjectName("terase_lab_size")
        self.terase_form_lastpage.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.terase_lab_size)
        self.terase_ledit_size = QtWidgets.QLineEdit(self.terase_frm_addr)
        self.terase_ledit_size.setMinimumSize(QtCore.QSize(90, 0))
        self.terase_ledit_size.setMaximumSize(QtCore.QSize(90, 23))
        self.terase_ledit_size.setText("0x00000000")
        self.terase_ledit_size.setReadOnly(False)
        self.terase_ledit_size.setObjectName("terase_ledit_size")
        self.terase_form_lastpage.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.terase_ledit_size)
        self.terase_lab_pages = QtWidgets.QLabel(self.terase_frm_addr)
        self.terase_lab_pages.setText("Кол-во стр.:")
        self.terase_lab_pages.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.terase_lab_pages.setObjectName("terase_lab_pages")
        self.terase_form_lastpage.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.terase_lab_pages)
        self.terase_ledit_pages = QtWidgets.QLineEdit(self.terase_frm_addr)
        self.terase_ledit_pages.setMinimumSize(QtCore.QSize(90, 0))
        self.terase_ledit_pages.setMaximumSize(QtCore.QSize(90, 23))
        self.terase_ledit_pages.setText("0")
        self.terase_ledit_pages.setReadOnly(False)
        self.terase_ledit_pages.setObjectName("terase_ledit_pages")
        self.terase_form_lastpage.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.terase_ledit_pages)
        self.horizontalLayout.addLayout(self.terase_form_lastpage)
        self.verticalLayout_6.addWidget(self.terase_frm_addr)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.tabs_cmd.addTab(self.tab_erase, "Стирание")
        self.tab_read = QtWidgets.QWidget()
        self.tab_read.setEnabled(False)
        self.tab_read.setMaximumSize(QtCore.QSize(16777215, 480))
        self.tab_read.setObjectName("tab_read")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_read)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tread_frm_file = QtWidgets.QFrame(self.tab_read)
        self.tread_frm_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tread_frm_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tread_frm_file.setObjectName("tread_frm_file")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tread_frm_file)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tread_lab_fileopen = QtWidgets.QLabel(self.tread_frm_file)
        self.tread_lab_fileopen.setText("Выбор файла для сохранения страниц (*.bin):")
        self.tread_lab_fileopen.setObjectName("tread_lab_fileopen")
        self.verticalLayout_8.addWidget(self.tread_lab_fileopen)
        self.tread_hbox_file = QtWidgets.QHBoxLayout()
        self.tread_hbox_file.setObjectName("tread_hbox_file")
        self.tread_ledit_filepath = QtWidgets.QLineEdit(self.tread_frm_file)
        self.tread_ledit_filepath.setMaximumSize(QtCore.QSize(16777215, 23))
        self.tread_ledit_filepath.setText("")
        self.tread_ledit_filepath.setReadOnly(False)
        self.tread_ledit_filepath.setObjectName("tread_ledit_filepath")
        self.tread_hbox_file.addWidget(self.tread_ledit_filepath)
        self.tread_btn_filesave = QtWidgets.QPushButton(self.tread_frm_file)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tread_btn_filesave.sizePolicy().hasHeightForWidth())
        self.tread_btn_filesave.setSizePolicy(sizePolicy)
        self.tread_btn_filesave.setMaximumSize(QtCore.QSize(20, 23))
        self.tread_btn_filesave.setText("...")
        self.tread_btn_filesave.setObjectName("tread_btn_filesave")
        self.tread_hbox_file.addWidget(self.tread_btn_filesave)
        self.verticalLayout_8.addLayout(self.tread_hbox_file)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tread_form_firstpage = QtWidgets.QFormLayout()
        self.tread_form_firstpage.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tread_form_firstpage.setObjectName("tread_form_firstpage")
        self.tread_lab_addr = QtWidgets.QLabel(self.tread_frm_file)
        self.tread_lab_addr.setText("Адрес")
        self.tread_lab_addr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tread_lab_addr.setObjectName("tread_lab_addr")
        self.tread_form_firstpage.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tread_lab_addr)
        self.tread_ledit_addr = QtWidgets.QLineEdit(self.tread_frm_file)
        self.tread_ledit_addr.setMinimumSize(QtCore.QSize(90, 0))
        self.tread_ledit_addr.setMaximumSize(QtCore.QSize(90, 23))
        self.tread_ledit_addr.setText("0x00000000")
        self.tread_ledit_addr.setReadOnly(False)
        self.tread_ledit_addr.setObjectName("tread_ledit_addr")
        self.tread_form_firstpage.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tread_ledit_addr)
        self.tread_lab_page = QtWidgets.QLabel(self.tread_frm_file)
        self.tread_lab_page.setText("Номер стр.:")
        self.tread_lab_page.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tread_lab_page.setObjectName("tread_lab_page")
        self.tread_form_firstpage.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tread_lab_page)
        self.tread_ledit_page = QtWidgets.QLineEdit(self.tread_frm_file)
        self.tread_ledit_page.setMinimumSize(QtCore.QSize(90, 0))
        self.tread_ledit_page.setMaximumSize(QtCore.QSize(90, 23))
        self.tread_ledit_page.setText("0")
        self.tread_ledit_page.setReadOnly(False)
        self.tread_ledit_page.setObjectName("tread_ledit_page")
        self.tread_form_firstpage.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tread_ledit_page)
        self.horizontalLayout_4.addLayout(self.tread_form_firstpage)
        self.tread_form_lastpage = QtWidgets.QFormLayout()
        self.tread_form_lastpage.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tread_form_lastpage.setObjectName("tread_form_lastpage")
        self.tread_lab_size = QtWidgets.QLabel(self.tread_frm_file)
        self.tread_lab_size.setText("Размер (байт)")
        self.tread_lab_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tread_lab_size.setObjectName("tread_lab_size")
        self.tread_form_lastpage.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tread_lab_size)
        self.tread_ledit_size = QtWidgets.QLineEdit(self.tread_frm_file)
        self.tread_ledit_size.setMinimumSize(QtCore.QSize(90, 0))
        self.tread_ledit_size.setMaximumSize(QtCore.QSize(90, 23))
        self.tread_ledit_size.setText("0x00000000")
        self.tread_ledit_size.setReadOnly(False)
        self.tread_ledit_size.setObjectName("tread_ledit_size")
        self.tread_form_lastpage.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tread_ledit_size)
        self.tread_lab_pages = QtWidgets.QLabel(self.tread_frm_file)
        self.tread_lab_pages.setText("Кол-во стр.:")
        self.tread_lab_pages.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tread_lab_pages.setObjectName("tread_lab_pages")
        self.tread_form_lastpage.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tread_lab_pages)
        self.tread_ledit_pages = QtWidgets.QLineEdit(self.tread_frm_file)
        self.tread_ledit_pages.setMinimumSize(QtCore.QSize(90, 0))
        self.tread_ledit_pages.setMaximumSize(QtCore.QSize(90, 23))
        self.tread_ledit_pages.setText("0")
        self.tread_ledit_pages.setReadOnly(False)
        self.tread_ledit_pages.setObjectName("tread_ledit_pages")
        self.tread_form_lastpage.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tread_ledit_pages)
        self.horizontalLayout_4.addLayout(self.tread_form_lastpage)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.tread_frm_file)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tabs_cmd.addTab(self.tab_read, "Чтение")
        self.tab_config = QtWidgets.QWidget()
        self.tab_config.setEnabled(False)
        self.tab_config.setMinimumSize(QtCore.QSize(480, 277))
        self.tab_config.setMaximumSize(QtCore.QSize(10000, 277))
        self.tab_config.setObjectName("tab_config")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_config)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.tconfig_vbox = QtWidgets.QVBoxLayout()
        self.tconfig_vbox.setObjectName("tconfig_vbox")
        self.tconfig_frm_oper = QtWidgets.QFrame(self.tab_config)
        self.tconfig_frm_oper.setMaximumSize(QtCore.QSize(16777215, 40))
        self.tconfig_frm_oper.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tconfig_frm_oper.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tconfig_frm_oper.setObjectName("tconfig_frm_oper")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tconfig_frm_oper)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tconfig_rbtn_read = QtWidgets.QRadioButton(self.tconfig_frm_oper)
        self.tconfig_rbtn_read.setMaximumSize(QtCore.QSize(16777215, 23))
        self.tconfig_rbtn_read.setText("Прочитать")
        self.tconfig_rbtn_read.setChecked(True)
        self.tconfig_rbtn_read.setObjectName("tconfig_rbtn_read")
        self.horizontalLayout_8.addWidget(self.tconfig_rbtn_read)
        self.tconfig_rbtn_write = QtWidgets.QRadioButton(self.tconfig_frm_oper)
        self.tconfig_rbtn_write.setMaximumSize(QtCore.QSize(16777215, 23))
        self.tconfig_rbtn_write.setText("Записать")
        self.tconfig_rbtn_write.setObjectName("tconfig_rbtn_write")
        self.horizontalLayout_8.addWidget(self.tconfig_rbtn_write)
        self.tconfig_vbox.addWidget(self.tconfig_frm_oper)
        self.verticalLayout_16.addLayout(self.tconfig_vbox)
        self.tabs_cmd.addTab(self.tab_config, "Конфигурация")
        self.verticalLayout_12.addWidget(self.tabs_cmd)
        self.btn_exec = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exec.setEnabled(False)
        self.btn_exec.setMaximumSize(QtCore.QSize(16777215, 23))
        self.btn_exec.setText("Выполнить")
        self.btn_exec.setObjectName("btn_exec")
        self.verticalLayout_12.addWidget(self.btn_exec)
        self.tedit_log = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.tedit_log.setMinimumSize(QtCore.QSize(488, 129))
        self.tedit_log.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Fixed")
        self.tedit_log.setFont(font)
        self.tedit_log.setReadOnly(True)
        self.tedit_log.setObjectName("tedit_log")
        self.verticalLayout_12.addWidget(self.tedit_log)
        self.pbar = QtWidgets.QProgressBar(self.centralwidget)
        self.pbar.setProperty("value", 0)
        self.pbar.setObjectName("pbar")
        self.verticalLayout_12.addWidget(self.pbar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 500, 25))
        self.menuBar.setObjectName("menuBar")
        self.menu_file = QtWidgets.QMenu(self.menuBar)
        self.menu_file.setTitle("Файл")
        self.menu_file.setObjectName("menu_file")
        self.menu_help = QtWidgets.QMenu(self.menuBar)
        self.menu_help.setTitle("Помощь")
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.act_exit = QtWidgets.QAction(MainWindow)
        self.act_exit.setText("Выход")
        self.act_exit.setShortcut("Ctrl+Q")
        self.act_exit.setObjectName("act_exit")
        self.act_about = QtWidgets.QAction(MainWindow)
        self.act_about.setText("О программе")
        self.act_about.setObjectName("act_about")
        self.menu_file.addAction(self.act_exit)
        self.menu_help.addAction(self.act_about)
        self.menuBar.addAction(self.menu_file.menuAction())
        self.menuBar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.combo_baud.setCurrentIndex(4)
        self.tabs_cmd.setCurrentIndex(0)
        self.act_exit.triggered.connect(MainWindow.close)
        self.act_about.triggered.connect(MainWindow.handle_act_about_triggered)
        self.btn_connect.clicked.connect(MainWindow.handle_btn_connect_clicked)
        self.rbtn_flash0.toggled['bool'].connect(MainWindow.handle_flash_select_toggled)
        self.rbtn_flash1.toggled['bool'].connect(MainWindow.handle_flash_select_toggled)
        self.btn_exec.clicked.connect(MainWindow.handle_btn_exec_clicked)
        self.twrite_ledit_filepath.textChanged['QString'].connect(MainWindow.handle_ledit_filepath_changed)
        self.tread_ledit_filepath.textEdited['QString'].connect(MainWindow.handle_ledit_filepath_changed)
        self.tread_btn_filesave.clicked.connect(MainWindow.handle_btn_filesave_clicked)
        self.btn_updport.clicked.connect(MainWindow.handle_btn_updport_clicked)
        self.rbtn_regionmain.clicked['bool'].connect(MainWindow.handle_region_select_toggled)
        self.rbtn_regionnvr.clicked['bool'].connect(MainWindow.handle_region_select_toggled)
        self.twrite_btn_fileopen.clicked.connect(MainWindow.handle_btn_fileopen_clicked)
        self.terase_rbtn_erpages.toggled['bool'].connect(MainWindow.handle_terase_mode_select_toggled)
        self.terase_rbtn_erall.toggled['bool'].connect(MainWindow.handle_terase_mode_select_toggled)
        self.tconfig_rbtn_read.toggled['bool'].connect(MainWindow.handle_tconfig_mode_select_toggled)
        self.tconfig_rbtn_write.toggled['bool'].connect(MainWindow.handle_tconfig_mode_select_toggled)
        self.tabs_cmd.currentChanged['int'].connect(MainWindow.handle_tabs_cmd_changed)
        self.twrite_ledit_addr.editingFinished.connect(MainWindow.handle_ledit_addr_edited)
        self.terase_ledit_addr.editingFinished.connect(MainWindow.handle_ledit_addr_edited)
        self.terase_ledit_size.editingFinished.connect(MainWindow.handle_ledit_size_edited)
        self.tread_ledit_addr.editingFinished.connect(MainWindow.handle_ledit_addr_edited)
        self.tread_ledit_size.editingFinished.connect(MainWindow.handle_ledit_size_edited)
        self.twrite_ledit_page.editingFinished.connect(MainWindow.handle_ledit_page_edited)
        self.terase_ledit_page.editingFinished.connect(MainWindow.handle_ledit_page_edited)
        self.terase_ledit_pages.editingFinished.connect(MainWindow.handle_ledit_pages_edited)
        self.tread_ledit_page.editingFinished.connect(MainWindow.handle_ledit_page_edited)
        self.tread_ledit_pages.editingFinished.connect(MainWindow.handle_ledit_pages_edited)
        self.twrite_chbox_jump.toggled['bool'].connect(MainWindow.handle_twrite_chbox_jump_toggled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.gbox_connect.setTitle(_translate("MainWindow", "Подключение"))
        self.btn_updport.setToolTip(_translate("MainWindow", "Обновить список портов"))
        self.gbox_flash.setTitle(_translate("MainWindow", "Выбор флеш"))
        self.gbox_region.setTitle(_translate("MainWindow", "Выбор области"))
        item = self.tinfo_tbl_flash.horizontalHeaderItem(0)
        item = self.tinfo_tbl_flash.horizontalHeaderItem(1)
        item = self.tinfo_tbl_flash.horizontalHeaderItem(2)
        item = self.tinfo_tbl_flash.horizontalHeaderItem(3)
        item = self.tinfo_tbl_flash.horizontalHeaderItem(4)
        self.twrite_ledit_filepath.setToolTip(_translate("MainWindow", "Файл для записи"))
        self.tread_ledit_filepath.setToolTip(_translate("MainWindow", "Файл для чтения"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

import ui_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

