# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config028.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Config028(object):
    def setupUi(self, Config028):
        Config028.setObjectName("Config028")
        Config028.resize(493, 418)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        Config028.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Config028)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tconfig_frm_cfg = QtWidgets.QFrame(Config028)
        self.tconfig_frm_cfg.setEnabled(True)
        self.tconfig_frm_cfg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tconfig_frm_cfg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tconfig_frm_cfg.setObjectName("tconfig_frm_cfg")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tconfig_frm_cfg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_warn0 = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_warn0.setTextFormat(QtCore.Qt.RichText)
        self.lbl_warn0.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_warn0.setObjectName("lbl_warn0")
        self.verticalLayout.addWidget(self.lbl_warn0)
        self.grid_cfgword = QtWidgets.QGridLayout()
        self.grid_cfgword.setObjectName("grid_cfgword")
        self.form_col0row1 = QtWidgets.QFormLayout()
        self.form_col0row1.setObjectName("form_col0row1")
        self.lbl_mask = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_mask.setObjectName("lbl_mask")
        self.form_col0row1.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_mask)
        self.ledit_mask = QtWidgets.QLineEdit(self.tconfig_frm_cfg)
        self.ledit_mask.setMaximumSize(QtCore.QSize(50, 23))
        self.ledit_mask.setObjectName("ledit_mask")
        self.form_col0row1.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ledit_mask)
        self.lbl_wrc = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_wrc.setObjectName("lbl_wrc")
        self.form_col0row1.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_wrc)
        self.ledit_wrc = QtWidgets.QLineEdit(self.tconfig_frm_cfg)
        self.ledit_wrc.setMaximumSize(QtCore.QSize(50, 23))
        self.ledit_wrc.setObjectName("ledit_wrc")
        self.form_col0row1.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ledit_wrc)
        self.lbl_tac = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_tac.setObjectName("lbl_tac")
        self.form_col0row1.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_tac)
        self.ledit_tac = QtWidgets.QLineEdit(self.tconfig_frm_cfg)
        self.ledit_tac.setMaximumSize(QtCore.QSize(50, 23))
        self.ledit_tac.setObjectName("ledit_tac")
        self.form_col0row1.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ledit_tac)
        self.grid_cfgword.addLayout(self.form_col0row1, 1, 0, 1, 1)
        self.form_col0row0 = QtWidgets.QFormLayout()
        self.form_col0row0.setObjectName("form_col0row0")
        self.lbl_bflashwe = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_bflashwe.setObjectName("lbl_bflashwe")
        self.form_col0row0.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_bflashwe)
        self.chbox_bflashwe = QtWidgets.QCheckBox(self.tconfig_frm_cfg)
        self.chbox_bflashwe.setMinimumSize(QtCore.QSize(0, 20))
        self.chbox_bflashwe.setText("")
        self.chbox_bflashwe.setChecked(True)
        self.chbox_bflashwe.setObjectName("chbox_bflashwe")
        self.form_col0row0.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.chbox_bflashwe)
        self.lbl_bnvrwe = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_bnvrwe.setObjectName("lbl_bnvrwe")
        self.form_col0row0.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_bnvrwe)
        self.chbox_bnvrwe = QtWidgets.QCheckBox(self.tconfig_frm_cfg)
        self.chbox_bnvrwe.setMinimumSize(QtCore.QSize(0, 20))
        self.chbox_bnvrwe.setText("")
        self.chbox_bnvrwe.setChecked(True)
        self.chbox_bnvrwe.setObjectName("chbox_bnvrwe")
        self.form_col0row0.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.chbox_bnvrwe)
        self.lbl_debugen = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_debugen.setObjectName("lbl_debugen")
        self.form_col0row0.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_debugen)
        self.chbox_debugen = QtWidgets.QCheckBox(self.tconfig_frm_cfg)
        self.chbox_debugen.setMinimumSize(QtCore.QSize(0, 20))
        self.chbox_debugen.setText("")
        self.chbox_debugen.setChecked(True)
        self.chbox_debugen.setObjectName("chbox_debugen")
        self.form_col0row0.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.chbox_debugen)
        self.lbl_bflashre = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_bflashre.setObjectName("lbl_bflashre")
        self.form_col0row0.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_bflashre)
        self.lbl_bnvrre = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_bnvrre.setObjectName("lbl_bnvrre")
        self.form_col0row0.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_bnvrre)
        self.chbox_bflashre = QtWidgets.QCheckBox(self.tconfig_frm_cfg)
        self.chbox_bflashre.setMinimumSize(QtCore.QSize(0, 20))
        self.chbox_bflashre.setText("")
        self.chbox_bflashre.setChecked(True)
        self.chbox_bflashre.setObjectName("chbox_bflashre")
        self.form_col0row0.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.chbox_bflashre)
        self.chbox_bnvrre = QtWidgets.QCheckBox(self.tconfig_frm_cfg)
        self.chbox_bnvrre.setMinimumSize(QtCore.QSize(0, 20))
        self.chbox_bnvrre.setText("")
        self.chbox_bnvrre.setChecked(True)
        self.chbox_bnvrre.setObjectName("chbox_bnvrre")
        self.form_col0row0.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.chbox_bnvrre)
        self.grid_cfgword.addLayout(self.form_col0row0, 0, 0, 1, 1)
        self.form_col1row0 = QtWidgets.QFormLayout()
        self.form_col1row0.setObjectName("form_col1row0")
        self.lbl_mflashwe = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_mflashwe.setObjectName("lbl_mflashwe")
        self.form_col1row0.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_mflashwe)
        self.chbox_mflashwe = QtWidgets.QCheckBox(self.tconfig_frm_cfg)
        self.chbox_mflashwe.setMinimumSize(QtCore.QSize(0, 20))
        self.chbox_mflashwe.setText("")
        self.chbox_mflashwe.setChecked(True)
        self.chbox_mflashwe.setObjectName("chbox_mflashwe")
        self.form_col1row0.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.chbox_mflashwe)
        self.lbl_mnvrwe = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_mnvrwe.setObjectName("lbl_mnvrwe")
        self.form_col1row0.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_mnvrwe)
        self.chbox_mnvrwe = QtWidgets.QCheckBox(self.tconfig_frm_cfg)
        self.chbox_mnvrwe.setMinimumSize(QtCore.QSize(0, 20))
        self.chbox_mnvrwe.setText("")
        self.chbox_mnvrwe.setChecked(True)
        self.chbox_mnvrwe.setObjectName("chbox_mnvrwe")
        self.form_col1row0.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.chbox_mnvrwe)
        self.lbl_jtagen = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_jtagen.setObjectName("lbl_jtagen")
        self.form_col1row0.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_jtagen)
        self.chbox_jtagen = QtWidgets.QCheckBox(self.tconfig_frm_cfg)
        self.chbox_jtagen.setMinimumSize(QtCore.QSize(0, 20))
        self.chbox_jtagen.setText("")
        self.chbox_jtagen.setChecked(True)
        self.chbox_jtagen.setObjectName("chbox_jtagen")
        self.form_col1row0.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.chbox_jtagen)
        self.lbl_mflashre = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_mflashre.setObjectName("lbl_mflashre")
        self.form_col1row0.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_mflashre)
        self.lbl_mnvrre = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_mnvrre.setObjectName("lbl_mnvrre")
        self.form_col1row0.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_mnvrre)
        self.chbox_mflashre = QtWidgets.QCheckBox(self.tconfig_frm_cfg)
        self.chbox_mflashre.setMinimumSize(QtCore.QSize(0, 20))
        self.chbox_mflashre.setText("")
        self.chbox_mflashre.setChecked(True)
        self.chbox_mflashre.setObjectName("chbox_mflashre")
        self.form_col1row0.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.chbox_mflashre)
        self.chbox_mnvrre = QtWidgets.QCheckBox(self.tconfig_frm_cfg)
        self.chbox_mnvrre.setMinimumSize(QtCore.QSize(0, 20))
        self.chbox_mnvrre.setText("")
        self.chbox_mnvrre.setChecked(True)
        self.chbox_mnvrre.setObjectName("chbox_mnvrre")
        self.form_col1row0.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.chbox_mnvrre)
        self.grid_cfgword.addLayout(self.form_col1row0, 0, 1, 1, 1)
        self.form_col1row1 = QtWidgets.QFormLayout()
        self.form_col1row1.setObjectName("form_col1row1")
        self.lbl_af = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_af.setObjectName("lbl_af")
        self.form_col1row1.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_af)
        self.combo_af = QtWidgets.QComboBox(self.tconfig_frm_cfg)
        self.combo_af.setMaximumSize(QtCore.QSize(16777215, 23))
        self.combo_af.setObjectName("combo_af")
        self.combo_af.addItem("")
        self.combo_af.addItem("")
        self.form_col1row1.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_af)
        self.lbl_mode = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_mode.setObjectName("lbl_mode")
        self.form_col1row1.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_mode)
        self.combo_mode = QtWidgets.QComboBox(self.tconfig_frm_cfg)
        self.combo_mode.setMaximumSize(QtCore.QSize(16777215, 23))
        self.combo_mode.setObjectName("combo_mode")
        self.combo_mode.addItem("")
        self.combo_mode.addItem("")
        self.form_col1row1.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_mode)
        self.lbl_rdc = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_rdc.setObjectName("lbl_rdc")
        self.form_col1row1.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_rdc)
        self.ledit_rdc = QtWidgets.QLineEdit(self.tconfig_frm_cfg)
        self.ledit_rdc.setMaximumSize(QtCore.QSize(50, 23))
        self.ledit_rdc.setObjectName("ledit_rdc")
        self.form_col1row1.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ledit_rdc)
        self.grid_cfgword.addLayout(self.form_col1row1, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.grid_cfgword)
        self.verticalLayout_2.addWidget(self.tconfig_frm_cfg)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.retranslateUi(Config028)
        self.combo_af.setCurrentIndex(1)
        self.combo_mode.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Config028)

    def retranslateUi(self, Config028):
        _translate = QtCore.QCoreApplication.translate
        Config028.setWindowTitle(_translate("Config028", "Form"))
        self.lbl_warn0.setText(_translate("Config028", "<html><head/><body><p><span style=\" color:#ef2929;\">Изменяйте состояние конфигурации с осторожностью!</span></p></body></html>"))
        self.lbl_mask.setToolTip(_translate("Config028", "<html><head/><body><p align=\"justify\">0 - запрещение записи и стирания основной области Flash-памяти</p><p align=\"justify\">1 - разрешение записи и стирания основной области Flash-памяти</p></body></html>"))
        self.lbl_mask.setText(_translate("Config028", "MASK"))
        self.ledit_mask.setText(_translate("Config028", "0xFFF"))
        self.lbl_wrc.setToolTip(_translate("Config028", "<html><head/><body><p align=\"justify\">0 - запрещение записи и стирания основной области Flash-памяти</p><p align=\"justify\">1 - разрешение записи и стирания основной области Flash-памяти</p></body></html>"))
        self.lbl_wrc.setText(_translate("Config028", "WRC"))
        self.ledit_wrc.setText(_translate("Config028", "0xF"))
        self.lbl_tac.setToolTip(_translate("Config028", "<html><head/><body><p align=\"justify\">0 - запрещение записи и стирания основной области Flash-памяти</p><p align=\"justify\">1 - разрешение записи и стирания основной области Flash-памяти</p></body></html>"))
        self.lbl_tac.setText(_translate("Config028", "TAC"))
        self.ledit_tac.setText(_translate("Config028", "0xF"))
        self.lbl_bflashwe.setToolTip(_translate("Config028", "<html><head/><body><p align=\"justify\">0 - запрещение записи и стирания основной области BFLASH</p><p align=\"justify\">1 - разрешение записи и стирания основной области BFLASH</p></body></html>"))
        self.lbl_bflashwe.setText(_translate("Config028", "BFLASHWE"))
        self.lbl_bnvrwe.setToolTip(_translate("Config028", "<html><head/><body><p align=\"justify\">0 - запрещение записи и стирания NVR области BFLASH</p><p align=\"justify\">1 - разрешение записи и стирания NVR области BFLASH</p></body></html>"))
        self.lbl_bnvrwe.setText(_translate("Config028", "BNVRWE"))
        self.lbl_debugen.setToolTip(_translate("Config028", "<html><head/><body><p>0 - запрещение работы функции отладки внутри ядра</p><p>1 - разрешение работы функции отладки внутри ядра</p></body></html>"))
        self.lbl_debugen.setText(_translate("Config028", "DEBUGEN"))
        self.lbl_bflashre.setToolTip(_translate("Config028", "<html><head/><body><p>0 - запрещение чтения основной области BFLASH</p><p align=\"justify\">1 - разрешение чтения основной области BFLASH</p></body></html>"))
        self.lbl_bflashre.setText(_translate("Config028", "BFLASHRE"))
        self.lbl_bnvrre.setToolTip(_translate("Config028", "<html><head/><body><p>0 - запрещение чтения NVR области BFLASH</p><p align=\"justify\">1 - разрешение чтения NVR области BFLASH</p></body></html>"))
        self.lbl_bnvrre.setText(_translate("Config028", "BNVRRE"))
        self.lbl_mflashwe.setToolTip(_translate("Config028", "<html><head/><body><p align=\"justify\">0 - запрещение записи и стирания основной области MFLASH</p><p align=\"justify\">1 - разрешение записи и стирания основной области MFLASH</p></body></html>"))
        self.lbl_mflashwe.setText(_translate("Config028", "MFLASHWE"))
        self.lbl_mnvrwe.setToolTip(_translate("Config028", "<html><head/><body><p align=\"justify\">0 - запрещение записи и стирания NVR области MFLASH</p><p align=\"justify\">1 - разрешение записи и стирания NVR области MFLASH</p></body></html>"))
        self.lbl_mnvrwe.setText(_translate("Config028", "MNVRWE"))
        self.lbl_jtagen.setToolTip(_translate("Config028", "<html><head/><body><p>0 - запрещение работы JTAG/SWD функции пина</p><p align=\"justify\">1 - разрешение работы JTAG/SWD функции пина</p></body></html>"))
        self.lbl_jtagen.setText(_translate("Config028", "JTAGEN"))
        self.lbl_mflashre.setToolTip(_translate("Config028", "<html><head/><body><p>0 - запрещение чтения основной области MFLASH</p><p align=\"justify\">1 - разрешение чтения основной области MFLASH</p></body></html>"))
        self.lbl_mflashre.setText(_translate("Config028", "MFLASHRE"))
        self.lbl_mnvrre.setToolTip(_translate("Config028", "<html><head/><body><p>0 - запрещение чтения NVR области MFLASH</p><p align=\"justify\">1 - разрешение чтения NVR области MFLASH</p></body></html>"))
        self.lbl_mnvrre.setText(_translate("Config028", "MNVRRE"))
        self.lbl_af.setToolTip(_translate("Config028", "<html><head/><body><p align=\"justify\">0 - запрещение записи и стирания основной области Flash-памяти</p><p align=\"justify\">1 - разрешение записи и стирания основной области Flash-памяти</p></body></html>"))
        self.lbl_af.setText(_translate("Config028", "AF"))
        self.combo_af.setItemText(0, _translate("Config028", "0: 1-ая функция"))
        self.combo_af.setItemText(1, _translate("Config028", "1: 2-ая функция"))
        self.lbl_mode.setToolTip(_translate("Config028", "<html><head/><body><p align=\"justify\">0 - запрещение записи и стирания основной области Flash-памяти</p><p align=\"justify\">1 - разрешение записи и стирания основной области Flash-памяти</p></body></html>"))
        self.lbl_mode.setText(_translate("Config028", "MODE"))
        self.combo_mode.setItemText(0, _translate("Config028", "0: 8-бит"))
        self.combo_mode.setItemText(1, _translate("Config028", "1: 16-бит"))
        self.lbl_rdc.setToolTip(_translate("Config028", "<html><head/><body><p align=\"justify\">0 - запрещение записи и стирания основной области Flash-памяти</p><p align=\"justify\">1 - разрешение записи и стирания основной области Flash-памяти</p></body></html>"))
        self.lbl_rdc.setText(_translate("Config028", "RDC"))
        self.ledit_rdc.setText(_translate("Config028", "0xF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Config028 = QtWidgets.QWidget()
    ui = Ui_Config028()
    ui.setupUi(Config028)
    Config028.show()
    sys.exit(app.exec_())

